branch-defaults:
  default:
    environment: BffServiceDev2-env
    group_suffix: null
environment-defaults:
  BffServiceDev2-env:
    branch: null
    repository: null
global:
  application_name: bff-service-dev2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
